### ISSUE TITLE
How to fix the error while trying to install using pip on windows

### ISSUE THREAD

**Issue by Razor5e** [kz26/dottorrent-cli#11]
Microsoft Windows [Version 10.0.19043.1165]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>pip install dottorrent-cli
Collecting dottorrent-cli
  Using cached dottorrent_cli-1.10.3-py3-none-any.whl (6.0 kB)
Collecting humanfriendly<3.0,>=2.1
  Using cached humanfriendly-2.4-py2.py3-none-any.whl (56 kB)
Collecting dottorrent>=1.9.2
  Using cached dottorrent-1.10.1-py3-none-any.whl (7.5 kB)
Collecting tqdm<5.0.0,>=4.8.4
  Using cached tqdm-4.62.2-py2.py3-none-any.whl (76 kB)
Collecting bencoder.pyx>=2.0.0
  Using cached bencoder.pyx-2.0.1.tar.gz (84 kB)
Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tqdm<5.0.0,>=4.8.4->dottorrent-cli) (0.4.4)
Using legacy 'setup.py install' for bencoder.pyx, since package 'wheel' is not installed.
Installing collected packages: bencoder.pyx, tqdm, humanfriendly, dottorrent, dottorrent-cli
    Running setup.py install for bencoder.pyx ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\users\user\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-t9et64pr\\bencoder-pyx_323ccc6b2a634338924c86e8f75a1eed\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-t9et64pr\\bencoder-pyx_323ccc6b2a634338924c86e8f75a1eed\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-vodkcro4\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\users\user\appdata\local\programs\python\python39\Include\bencoder.pyx'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-t9et64pr\bencoder-pyx_323ccc6b2a634338924c86e8f75a1eed\
    Complete output (5 lines):
    running install
    running build
    running build_ext
    building 'bencoder' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\users\user\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-t9et64pr\\bencoder-pyx_323ccc6b2a634338924c86e8f75a1eed\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-t9et64pr\\bencoder-pyx_323ccc6b2a634338924c86e8f75a1eed\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-vodkcro4\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\users\user\appdata\local\programs\python\python39\Include\bencoder.pyx' Check the logs for full command output.

C:\WINDOWS\system32>

**Comment by mahkitah** [comment]
I'm not sure why, but the bencoder will not install on python 3.9
Switching to py 3.8 will solve the problem.
There's probably a real solution to get bencoder working on py 3.9, but I haven't found it.

**Comment by omgitsraven** [comment]
I'm getting a very similar error, still:

```
> pip install dottorrent-cli
Requirement already satisfied: dottorrent-cli in c:\users\hazel\appdata\local\programs\python\python313\lib\site-packages\dottorrent_cli-1.10.3-py3.13.egg (1.10.3)
Requirement already satisfied: dottorrent>=1.9.2 in c:\users\hazel\appdata\local\programs\python\python313\lib\site-packages\dottorrent-1.10.1-py3.13.egg (from dottorrent-cli) (1.10.1)
Collecting humanfriendly<3.0,>=2.1 (from dottorrent-cli)
  Using cached humanfriendly-2.4-py2.py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.8.4 in c:\users\hazel\appdata\local\programs\python\python313\lib\site-packages (from dottorrent-cli) (4.67.1)
Requirement already satisfied: colorama in c:\users\hazel\appdata\local\programs\python\python313\lib\site-packages (from tqdm<5.0.0,>=4.8.4->dottorrent-cli) (0.4.6)
Collecting bencoder.pyx>=2.0.0 (from dottorrent>=1.9.2->dottorrent-cli)
  Using cached bencoder.pyx-3.0.1.tar.gz (85 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      <string>:7: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!

              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
              ********************************************************************************

      !!

      Error compiling Cython file:
      ------------------------------------------------------------
      ...


      encode_func = {
          int: encode_int,
          bool: encode_int,
          long: encode_long,
          ^
      ------------------------------------------------------------

      bencoder.pyx:152:4: undeclared name not builtin: long
      pip_system_certs: ERROR: could not register module: No module named 'wrapt'
      Compiling bencoder.pyx because it changed.
      [1/1] Cythonizing bencoder.pyx
      Traceback (most recent call last):
        File "C:\Users\Hazel\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "C:\Users\Hazel\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hazel\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Hazel\AppData\Local\Temp\pip-build-env-fkpwljdb\overlay\Lib\site-packages\setuptools\build_meta.py", line 331, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Hazel\AppData\Local\Temp\pip-build-env-fkpwljdb\overlay\Lib\site-packages\setuptools\build_meta.py", line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\Hazel\AppData\Local\Temp\pip-build-env-fkpwljdb\overlay\Lib\site-packages\setuptools\build_meta.py", line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 24, in <module>
        File "C:\Users\Hazel\AppData\Local\Temp\pip-build-env-fkpwljdb\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
          ~~~~~~~~~~~~~^^^^^^^
        File "C:\Users\Hazel\AppData\Local\Temp\pip-build-env-fkpwljdb\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1298, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: bencoder.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Are there any solutions yet, besides maintaining multiple versions of Python?
