### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by awsms** [kz26/dottorrent-cli#4]
```
Traceback (most recent call last):
  File "/home/xxx/.local/bin/dottorrent", line 6, in <module>
    from dtcli.cli import main
  File "/home/xxx/.local/lib/python2.7/site-packages/dtcli/cli.py", line 32, in <module>
    import dottorrent
  File "/home/xxx/.local/lib/python2.7/site-packages/dottorrent/__init__.py", line 62
    print(v, file=sys.stderr)
                 ^
SyntaxError: invalid syntax
```

What's the problem here? :(

**Comment by mahkitah** [comment]
You're using python 2.7. Dottorrent is for Python 3
