### ISSUE TITLE
Special characters ( { é ù) won't work

### ISSUE THREAD

**Issue by awsms** [kz26/dottorrent-cli#5]
```
Traceback (most recent call last):
  File "/home/***/.local/bin/dottorrent", line 8, in <module>
    sys.exit(main())
  File "/home/***/.local/lib/python3.5/site-packages/dtcli/cli.py", line 91, in main
    print("Input: {}".format(args.path))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce2' in position 48: surrogates not allowed
```

**Comment by mahkitah** [comment]
Can you test if this works. Put the following line at the top of the file beneath the imports and above the main function:

sys.stdout = io.TextIOWrapper(sys.stdout.detach(), sys.stdout.encoding, 'replace')
